# For more information: https://laravel.com/docs/sail
version: '3'
services:
    traefik:
        image: "traefik:v2.6"
        container_name: "traefik"
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - sail

    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        #ports:
        #    - '${APP_PORT:-80}:80'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.rule=Host(`vps-70f2628e.vps.ovh.net`)"
            - "traefik.http.routers.laravel.entrypoints=web"
            - "traefik.http.services.laravel.loadbalancer.server.port=80"
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - selenium
    mysql:
        image: 'mysql/mysql-server:8.0'
        #ports:
        #    - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        #ports:
        #    - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        #ports:
        #    - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sail-meilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        #ports:
        #    - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        #    - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
    phpmyadmin:
        image: phpmyadmin
        restart: always
#        ports:
#            - 8081:80
        labels:
          # Route with Traefik
          - traefik.enable=true
          - traefik.http.routers.phpmyadmin.rule=Host(`vps-70f2628e.vps.ovh.net`) && PathPrefix(`/pma`) # <-- !
#          - traefik.http.routers.phpmyadmin.rule=PathPrefix(`/pma`)
          - traefik.http.routers.phpmyadmin.entrypoints=web
          - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
          # Middleware
          - traefik.http.middlewares.phpmyadmin.stripprefix.prefixes=/pma
          - traefik.http.middlewares.phpmyadmin.stripprefix.forceslash=true
          - traefik.http.routers.phpmyadmin.middlewares=phpmyadmin@docker
        environment:
          - PMA_HOST=mysql
          - PMA_ABSOLUTE_URI=http://vps-70f2628e.vps.ovh.net/pma/
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
